### ISSUE TITLE
VirtualPad and KeyEditor

### ISSUE THREAD

**Issue by DocSkellington** [DocSkellington/pcsx2-1.4.0-rr#4]
This continues the work on #3.

So, I added some wxSpinCtrl to handle pressure in the Virtual Pad.
@xTVaser, could you please check if this works?

I'll do the KeyEditor later.

**Comment by xTVaser** [comment]
Sure no problem, I'll test that out within a few days.

Also just so you know, I did a quick merge with pcsx2's master branch and looks like the only real breaking change is that they have removed a lot of the `Reset` functionality, although there is still a reset button when you go to switch ISOs so it must still be in the codebase somewhere.

It would be nice if this was a true fork of pcsx2 rather than a fork off of pocokhc so we could pull in changes upstream without it being a huge pain.

**Comment by DocSkellington** [comment]
Thank you!

Did they modify the way `Reset` works? If so, we may be able to avoid de-sync. I've already tried to add the `Reset` flag in the movies but it always de-synced.

We can always create a new repository directly from PCSX2 and add our changes done here ;).

**Comment by xTVaser** [comment]
I havnt yet searched for how their reset functionality works now, but they definitely removed the functionality from the UI as much as they can.... [this method](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/gui/MainFrame.cpp#L582) seems to have undergone a major refactor, and [`UI_DisableSystemReset`](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/gui/MainMenuClicks.cpp#L575) appears to be gone.

I'm just running into build issues right now with their latest master branch where the performance is incredibly slow.  So definitely need to get that fixed first.

**Comment by DocSkellington** [comment]
(I've closed this issue to transfer it into the new fork)
